### ISSUE TITLE
the crawlers delayed death

### ISSUE THREAD

**Issue by chrisfoster121** [Verb-Noun-Studios/Symbiotic#187]
the crawlers will take a couple of seconds to explode when the player kills them

**Comment by fnoogie** [comment]
When crawler is killed, they stop moving an begin their explosion animation. During this time their collider is still fully active resulting in some shots being blocked by dying crawlers

**Comment by iXiphos** [comment]
This doesn't seem urgent, updating status accordingly

**Comment by fnoogie** [comment]
Crawler death explosion happens instantly, no relevant animation plays
