### ISSUE TITLE
Spawning on the floor instead of on the bridge part 

### ISSUE THREAD

**Issue by MRusso16** [Verb-Noun-Studios/Symbiotic#91]
When you click "play" sometimes, you'd spawn on the floor area and obviously you wouldn't be able to get back up cuz there's no ramp. It wouldn't matter if there was a ramp, but since there is none, players would have to restart the level then they would spawn in the normal area (bridge part)

**Comment by iXiphos** [comment]
I am updating that this week, will close this when complete
