### ISSUE TITLE
Tab key 

### ISSUE THREAD

**Issue by MRusso16** [Verb-Noun-Studios/Symbiotic#95]
Hitting tab obviously shows the upgrades you have. when the upgrades are shown, you can only move WASD and nothing else. You can hold down the right click button which allows you to shoot and look around while moving as well. Not sure if this is a bug but I think it is. It's just something whether we want to make it where if you hit tab it pauses the game entirely until you hit tab again OR when you hit tab, the gameplay resumes but make it where you cant do anything with your character even when you hold right click too OR a different alternative I'm not thinking of.

**Comment by iXiphos** [comment]
This is not a bug, it lets the player hover over upgrades so they can see what they do.

**Comment by MRusso16** [comment]
Yeah nah true, it just may need some tweaking but it don’t matter anyways
